# Generated by Django 3.1.13 on 2022-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220326_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('policy', models.CharField(max_length=12)),
                ('appointment_date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
    ]
